#! /bin/bash

IFCONF=/sbin/ifconfig
LED_SHOW=/usr/local/bin/led_msg.py

function get_ip() {
$IFCONF $1 | grep "inet addr:" | sed 's/^.*addr://g' | sed 's/Bcast.*$//g'
}

function netdev_list() {
ifconfig | sed 's/[ \t].*//;/^\(lo\|\)$/d'
}

trap "echo Ctrl + C; exit" INT

for loop in `seq 6`
    do
	print_value=""
	devs=$(netdev_list)

	for dev_name in $devs
	    do
		$IFCONF ${dev_name} | grep "inet addr" > /dev/null
		if (($? == 0)); then
	    	    print_value="${print_value}${dev_name}:`get_ip ${dev_name}` "
		fi
	    done

	$LED_SHOW -m "${print_value}" -b 5
	sleep 10
    done

